### ISSUE TITLE
[Bug]: [KVM] Computer stuck on boot menu: GRUB loading

### ISSUE THREAD

**Issue by lilian-pouliquen** [MassOS-Linux/MassOS#34]
### Checklist

- [X] I have searched for [other issues](https://www.github.com/MassOS-Linux/MassOS/issues), and can confirm my issue has not already been reported.
- [X] If this is an issue with a specific program, I have checked the upstream project's issue tracker and determined that it is an issue with MassOS itself.

### MassOS version

2022.06

### Kernel version

Linux 5.18.1-massos #1 SMP PREEMPT_DYNAMIC wed Jun 1 16:11:46 UTC 2022 x86_64

### Subject

- [X] Issue at runtime of MassOS.
- [ ] Issue with the MassOS Live CD.
- [X] Issue with installing MassOS.
- [ ] Issue with the MassOS documentation.
- [ ] Issue compiling MassOS from source.

### Expected Behavior

I wanted to test MassOS on a virtual machine. So I built one and used the standard ISO to install MassOS on the virtual disk. Everything is fine until the virtual machine reboots after the installation.
At this point it should be restarting and boot into MassOS correctly, allowing me to use it.

### Actual Behavior

The fact is, when the virtual machine reboots, it gets stuck in the boot menu with the message "GRUB loading." staying forever. I did not manage to make it work, even by reinstalling the OS with different configurations nor by recreating the virtual machine.
![grub_loading](https://user-images.githubusercontent.com/38006711/173154936-713dd56c-c672-4132-ab2b-59db4a8aef78.png)
.

### Steps to reproduce

1. Create a virtual machine using virt-manager (see attached xml file)
2. Start the virtual machine with the standard ISO: massos-2022.06-x86_64.iso
3. Install the system on the virtual disk using the MassOS installer
    1. Install option
    2. Choose the virtual disk and erase it to install
    3. xfs or ext4 filesystem
    4. Say yes to create swap partition
    5. Say yes to erase all data on the disk
    6. fr_FR.UTF-8 locale
    7. fr FRENCH keyboard
    8. Europe/Paris timezone
    9. Set root password
    10. Create the primary user
    11. Say yes or no to make Blueman autostart on login
    12. Say yes or no to make the bootloader detect other OSs
4. Remove the ISO from the virtual machine, or change the boot order
5. Let the virtual machine reboot after the installation

[massos_kvm.txt](https://github.com/MassOS-Linux/MassOS/files/8882476/massos_kvm.txt)

**Comment by marseye** [comment]
Hi,

I have the exact same stuck grub problem when starting Massos, except it's as a VM with VMWARE Workstation 15.5.7 build-17171714. Same settings as lilian-pouliquen above, with these VM settings :
- type : linux 64 bits, kernel >5.x
- Bridged network
- 4 Processors
- 4GB RAM 
- 20GB scsi

I'm using the massos-2022.06-x86_64.iso

As soon as the first reboot initiates (.iso detached), Grub seems to initiate, but then :
"A fault has occurred causing a virtual CPU to enter the shutdown state. If this fault had occurred outside of a virtual machine, it would have caused the physical machine to restart. The shutdown state can be reached by incorrectly configuring the virtual machine, a bug in the guest operating system, or a problem in VMware Workstation."

I've been trying with and without the grub install : it always installs the same, and its stuck under 2s after the "GRUB Loading." message.

**Comment by RetronEletron** [comment]
I don't see to be able to replicate this issue on my side as well with a VM (virt-manager nor gnome-boxes) so i can't help you with that.

**Comment by DanielMYT** [comment]
Thanks for bringing this issue up.

I was able to replicate this issue in Oracle VirtualBox, however it only occurs when the virtual hard disk's interface is IDE and the boot mode is Legacy. If the Virtual hard disk is connected via SATA (which is the default), the boot is fine, and if the boot mode is UEFI (which is preferred for MassOS), the boot works in both IDE and SATA.

From the attached `massos_kvm.txt` file, it looks like your disk is configured in IDE, so I'd recommend switching it to SATA, and/or switch the boot mode to UEFI if your VM software supports that.

I will leave this issue open though since IDE+Legacy boot shouldn't be failing, however my discussed workaround should allow MassOS to boot in your virtual machine (NOTE: if you switch the interface or boot mode you may need to reinstall MassOS). Hope this helps you.

**Comment by TheRealSlander** [comment]
@lilian-pouliquen I suspected something like that for the French locale/keyboard as when the installation process is generating locales, only the "english" ones are displayed. Unfortunately, I could not test the OS after installation due to the issue I reported above, so I cannot confirm that fact. But I think it should be reported as an issue indeed.

Otherwise, can you tell me how you did manage to use an UEFI boot on your virtual machine? I use Qemu and Virtual-Manager for my virtual machines by the way.

**Comment by lilian-pouliquen** [comment]
> @lilian-pouliquen I suspected something like that for the French locale/keyboard as when the installation process is generating locales, only the "english" ones are displayed. Unfortunately, I could not test the OS after installation due to the issue I reported above, so I cannot confirm that fact. But I think it should be reported as an issue indeed.
> 
> Otherwise, can you tell me how you did manage to use an UEFI boot on your virtual machine? I use Qemu and Virtual-Manager for my virtual machines by the way.

Okay I'll make another issue for the keyboard layout then.

You can select the boot firmware at the virtual machine creation. In virt-manager. To do so, check the "Customise configuration before installation" checkbox at the 5th step of the VM creation:

![customise_config](https://user-images.githubusercontent.com/38006711/173621043-7a387615-e3c3-4e98-b6b2-067265eddc8f.png)

Then, click on "Finish". it is now opening the customisation window, where you can tweak all your VM.
To set the boot firmware to UEFI, go to the "Overview" tab and select an UEFI option in the "Firmware" option:

![choose_boot_firmware](https://user-images.githubusercontent.com/38006711/173622550-c9bb3a3b-533f-4b38-8b05-15a08b533845.png)

Do not forget to apply changes (virt-manager should remind you to do it if you try to do anything else).
You can then explore the configuration as you want.

I usually change these settings when I create a VM:

- Overview tab:
    - Chipset: Q35
    - Firmware: UEFI x86_64 : /usr/share/edk2/ovmf/OVMF_CODE.fd
- Processors tab:
    - Configuration: Copy host processor config if it is host-passthrough, select host-passthrough else
    - Topology:
        - Check the define processor topology manually checkbox
        - sockets: 1
        - cores: number_of_wanted_vcpu / number_of_threads
        - threads: 2
- Disks:
    - Disk bus: SATA or VirtIO

I hope this will help you!

**Comment by TheRealSlander** [comment]
Thanks a lot @lilian-pouliquen! I tried what you suggested to do for the configuration in virt-manager but first when I clicked on "start installation", I had this error message:
```
Unable to continue installation: « unsupported configuration: IDE controllers are unsupported for this QEMU binary or machine type »

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
  File "/usr/lib/python3.10/site-packages/libvirt.py", line 4413, in createXML
```
I found that this is due to the fact that I didn't select "sata" for the DVD disk as well (only did it for the hard drive entry). Mentioning it just in case someone encounter the same error message.

I was then able to start the live DVD and start the install process. I then had a screen wanting to know if the install was on an internal hard drive or an external/SSD disk, was the first time I was seeing this question. I selected "internal".

I was able to finish the install and to boot in the newly set system. Yeah! Thank you again.

But I confirm selecting French locale/keyboard during the install does not work. If you fill a report, I will get there and confirm it. I think I will try some other languages as well to be sure that this is not just the French one which fails.

By the way, timezone is good (selected Europe/paris).

**Comment by DanielMYT** [comment]
Please open a separate issue since these are unrelated.

**Comment by DanielMYT** [comment]
GRUB stalling on i386-pc (Legacy BIOS) should be fixed, now that (3 years on) we use more up to date builds of GRUB, and use less aggressive compiler optimizations for GRUB. From my testing across VMware/VirtualBox/QEMU, it boots more reliably on newer MassOS experimental builds when using Legacy BIOS.

The [recently written documentation](https://github.com/MassOS-Linux/MassOS/wiki/MassOS-on-Virtual-Machines) about running MassOS on virtual machines includes suggestions to use SATA controllers where possible, and to use UEFI boot if possible too.
